apiVersion: v1
kind: Secret
metadata:
  name: food-ordering-secrets
type: Opaque
data:
  postgres-password: MTIzNA==
  jwt-secret: NDA0RTYzNTI2NjU1NkE1ODZOMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNkkwUA==