server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**, /auth/**
        - id: menu-service
          uri: http://menu-service:8082
          predicates:
            - Path=/restaurant/**, /menuItems/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always